FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/Wallabag/Wallabag.csproj", "src/Wallabag/"]
RUN dotnet restore "src/Wallabag/Wallabag.csproj"
COPY . .
WORKDIR "/src/src/Wallabag"
RUN dotnet build "Wallabag.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Wallabag.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN mkdir ./data
ENTRYPOINT ["dotnet", "Wallabag.dll"]
