FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/Linkding/Linkding.csproj", "src/Linkding/"]
RUN dotnet restore "src/Linkding/Linkding.csproj"
COPY . .
WORKDIR "/src/src/Linkding"
RUN dotnet build "Linkding.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Linkding.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN mkdir ./data
ENTRYPOINT ["dotnet", "Linkding.dll"]
