version: '3.9'

services:
  linkdingupdater:
    image: ghcr.io/spaytac/linkding-updater:latest
    volumes:
      - ./config.yml:/app/data/config.yml
    # env_file:
    #   - .env
    environment:
      - Worker__Intervall=0
      - Linkding__Url=https://<url>
      - Linkding__Key=<secret>
