version: '3.9'

services:
  linkdingupdater:
    image: ghcr.io/spaytac/linkding-updater:latest
    volumes:
      - ./config.yml:/app/data/config.yml
    # env_file:
    #   - .env
    environment:
      - Worker__Interval=0
      - Worker__TagNameLength=64
      - Worker__Tasks__0=AddPopularSitesAsTag
      - Worker__Tasks__1=AddYearToBookmark
      - Linkding__Url=https://<url>
      - Linkding__Key=<secret>
